cursor_text_color #bec8ca

foreground            #dee4e4
background            #0e1415
url_color             #81d3de

color0                #2C2C30
color1                #A97070
color2                #778C73
color3                #CC9166
color4                #6C7F93
color5                #B894AF
color6                #8EA4A2
color7                #AFA79D

color8                #A5A59C
color9                #BC8F8F
color10               #778C73
color11               #D9AC8C
color12               #8A99A8
color13               #CCB3C6
color14               #8FA4A2
color15               #fefffe

cursor                #778C73
selection_foreground #AFA79D
selection_background  #4D4D4D
