local colors = require("colors")
local animations = require("animations")

hl.config({
	autogenerated = false,
  animations = animations,
	input = {
		kb_layout = "pl,ru",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:ctrl_space_toggle",
		kb_rules = "",
		repeat_delay = 250,
		repeat_rate = 80,

		follow_mouse = 1,

		sensitivity = -0.9, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
  general = {
      gaps_in = 5,
      gaps_out = 5,

      border_size = 2,

      -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
      col = {
        active_border = colors.tertiary,
        inactive_border = colors.tertiary_container,
      },

      -- Set to true enable resizing windows by clicking and dragging on borders and gaps
      resize_on_border = true,

      -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
      allow_tearing = false,

      layout = "dwindle",
      -- layout = scrolling
      -- layout = master
  }
})
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

