##############################
###         WINDOWS        ###
##############################
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Don't allow idle on fullscreen windows
windowrule = match:fullscreen true, idle_inhibit fullscreen

# Run all steam apps on 1st workspace and make them fullscreen
windowrule = match:class (^steam_app_[0-9]+$), workspace 1
windowrule = match:class (^cs2$), workspace 1
windowrule = match:class (^steam_app_[0-9]+$), fullscreen on

# Run steam on 4th workspace
windowrule = match:title Steam, workspace 4

# Run browser on workspace 2
windowrule = match:class ^zen$, workspace 2

# Run terminal on workspace 3
windowrule = match:title ^kitty-term$, workspace 3

# Run spoty player on workspace 5
windowrule = match:title ^spotify_player$, workspace 5

# bluetui settings
windowrule = match:title ^bluetui_term$, float on, center on, size 700 800
windowrule = match:title ^wiremix_term$, float on, center on, size 1000 700
# btop_term
windowrule = match:title ^btop_term$, float on, center on, size 1200 800

# Run discord on workspace 5
windowrule = match:class discord, workspace 5
windowrule = match:class vesktop, workspace 5

# Transparency
windowrule = match:class org.gnome.Nautilus, opacity 0.9

# Launcher
windowrule = match:title launcher, float on, size 600 300


# make screen white selection dim disapear faster
layerrule = animation popout, match:namespace selection
