import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 15


[cursor]
style.blinking = "On"
blink_timeout = 0
unfocused_hollow = true
blink_interval = 500

