[general]
import = [
    "~/.config/alacritty/themes/posterpole.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

opacity = 1
blur = false
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 15

[font.offset]
x = 0
y = 1

