import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]
[env]
TERM = "xterm-256color"

[window]
decorations = "none"

# opacity = 0.8
# blur = true
option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"
size = 15

[font.offset]
x = 0
y = 1

