return {
    
    background = "rgba(161313ff)"
    
    error = "rgba(ff7063ff)"
    
    error_container = "rgba(7b0007ff)"
    
    inverse_on_surface = "rgba(504c4cff)"
    
    inverse_primary = "rgba(7b6367ff)"
    
    inverse_surface = "rgba(e8e1e1ff)"
    
    on_background = "rgba(666161ff)"
    
    on_error = "rgba(3a0001ff)"
    
    on_error_container = "rgba(ffb1a8ff)"
    
    on_primary = "rgba(29181bff)"
    
    on_primary_container = "rgba(dbbec2ff)"
    
    on_primary_fixed = "rgba(ffe3e7ff)"
    
    on_primary_fixed_variant = "rgba(d4b6bbff)"
    
    on_secondary = "rgba(201517ff)"
    
    on_secondary_container = "rgba(d4c0c3ff)"
    
    on_secondary_fixed = "rgba(fae4e7ff)"
    
    on_secondary_fixed_variant = "rgba(cdb9bbff)"
    
    on_surface = "rgba(c9c2c2ff)"
    
    on_surface_variant = "rgba(a29c9cff)"
    
    on_tertiary = "rgba(271117ff)"
    
    on_tertiary_container = "rgba(e2bbc2ff)"
    
    on_tertiary_fixed = "rgba(ffe3e7ff)"
    
    on_tertiary_fixed_variant = "rgba(dab4bbff)"
    
    outline = "rgba(807a7aff)"
    
    outline_variant = "rgba(3d3939ff)"
    
    primary = "rgba(b2969bff)"
    
    primary_container = "rgba(493539ff)"
    
    primary_fixed = "rgba(614b4fff)"
    
    primary_fixed_dim = "rgba(493539ff)"
    
    scrim = "rgba(000000ff)"
    
    secondary = "rgba(ab999bff)"
    
    secondary_container = "rgba(443739ff)"
    
    secondary_fixed = "rgba(5c4d50ff)"
    
    secondary_fixed_dim = "rgba(443739ff)"
    
    shadow = "rgba(000000ff)"
    
    source_color = "rgba(933752ff)"
    
    surface = "rgba(161313ff)"
    
    surface_bright = "rgba(3c3839ff)"
    
    surface_container = "rgba(221f1fff)"
    
    surface_container_high = "rgba(2d2929ff)"
    
    surface_container_highest = "rgba(383434ff)"
    
    surface_container_low = "rgba(1e1b1bff)"
    
    surface_container_lowest = "rgba(100d0eff)"
    
    surface_dim = "rgba(161313ff)"
    
    surface_tint = "rgba(ddbfc4ff)"
    
    surface_variant = "rgba(4a4646ff)"
    
    tertiary = "rgba(b8949bff)"
    
    tertiary_container = "rgba(4d3338ff)"
    
    tertiary_fixed = "rgba(66494fff)"
    
    tertiary_fixed_dim = "rgba(4d3338ff)"
    
}
